# 实验名称
experiment: "hme"

# 随机种子
seed: 0

# 训练参数
epoches: 0
batch_size: 6
workers: 0
optimizer: Adadelta
lr: 1
lr_decay: cosine
step_ratio: 3
step_decay: 10
eps: 1e-6
weight_decay: 2e-5
beta: 0.9
image_resize: True
image_width: 1600
image_height: 320
image_channel: 1
dropout: True
dropout_ratio: 0.0
relu: True
gradient: 100
gradient_clip: True
use_label_mask: True

# 训练数据
train_image_path: "/openbayes/input/input1/train_image.pkl"
train_label_path: "/openbayes/input/input1/train_label.pkl"
eval_image_path: "/openbayes/input/input0/test_image.pkl"
eval_label_path: "/openbayes/input/input0/test_label.pkl"

word_path: "/openbayes/input/input1/word.txt"

# 选择encoder
encoder:
  net: DenseNet
  input_channels: 1
  out_channels: 684

resnet:
  conv1_stride: 1

densenet:
  ratio: 16
  growthRate: 24
  reduction: 0.5
  bottleneck: True
  use_dropout: True

# 使用的rnn cell
decoder:
  net: SAN_decoder
  cell: "GRU"
  input_size: 256
  hidden_size: 256

# attention 参数
attention:
  attention_dim: 512
  word_conv_kernel: 1
  struct_conv_kernel: 3
  use_coverage: True

# structure
structure:
  struct_dropout_ratio: 0
  with_hidden: True

# hybrid tree
hybrid_tree:
  threshold: 0.5

# 训练权重存放路径
optimizer_save: True
checkpoint_dir: "checkpoints"
finetune: True
checkpoint: "checkpoints/hme_best.pth"

# tensorboard路径
log_dir: "/openbayes/home/tf_dir"

# modified
epoch_offset_for_lr: 0
total_epochs: 0
eval_only: False
